services:
  ubuntu-rawrefinary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rawrefinary
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /home/rafael/rdesktop/:/config/out/ #optional
    ports:
      - 3392:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

    # default user/password: abc
