services:
  ubuntu-rawrefinary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rawrefinary
    # security_opt:
    #   - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/:/out/
    ports:
      - 14500:14500
    # devices:
    #   - /dev/dri:/dev/dri #optional
    # shm_size: "1gb" #optional
    # restart: unless-stopped

    # default user/password: abc
