# Hardware bits originally generated by 'nixos-generate-config' for the bbtablet,
# plus host-specific settings (DE, locale, user) that differ from the shared
# nixos/configuration.nix.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      # Community hardware module for the Surface Go 1. Brings in the
      # linux-surface patched kernel, Kaby Lake CPU/GPU bits, ath10k WiFi
      # firmware override, SSD profile and Surface-specific power tuning.
      # Requires the `nixos-hardware` channel:
      #   sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
      #   sudo nix-channel --update
      <nixos-hardware/microsoft/surface/surface-go>
    ];

  # Pin the LTS variant of the linux-surface kernel.
  # Note: do NOT also set boot.kernelPackages here — the surface module
  # owns the kernel and the two would conflict.
  hardware.microsoft-surface.kernelVersion = "longterm";

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aa974abe-e7e5-4823-8012-d41a7a2cc7a3";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3693-8B1E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5e97a962-a45b-43ac-b3a8-16da7888aa65"; }
    ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Intel microcode is enabled by the kaby-lake submodule pulled in via
  # nixos-hardware/microsoft/surface/surface-go.

  networking.hostName = "bbtablet";

  # Locale / keymap (Danish) - host-specific
  i18n.defaultLocale = "en_DK.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };
  console.keyMap = "dk-latin1";
  services.xserver.xkb = {
    layout = "dk";
    variant = "";
  };

  # Desktop environment: GNOME + GDM
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # Local user for the tablet (the shared config defines rafael as well).
  users.users.bb = {
    isNormalUser = true;
    description = "bb";
    extraGroups = [ "networkmanager" "wheel" ];
  };

  programs.firefox.enable = true;

  # --- Surface Go specific tuning ---

  # Touchscreen + pen via the Intel Precise Touch & Stylus daemon.
  services.iptsd.enable = true;

  # Bluetooth (Marvell module on Surface Go).
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;

  # Surface Go is fanless; thermald keeps it under throttle thresholds
  # without clamping frequency too aggressively.
  services.thermald.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Backlight + power keys (programs.light was removed from nixpkgs).
  hardware.acpilight.enable = true;
  services.acpid.enable = true;

  # Touch ergonomics for GNOME on Wayland.
  services.libinput = {
    enable = true;
    touchpad.naturalScrolling = true;
  };

  # Intel Kaby Lake GPU acceleration (VA-API video decode).
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      libva-vdpau-driver
      libvdpau-va-gl
    ];
  };

  # Pull in non-redistributable firmware as well (covers IPU3 cameras).
  hardware.enableAllFirmware = true;
}
