# Hardware bits originally generated by 'nixos-generate-config' for the bbtablet,
# plus host-specific settings (DE, locale, user) that differ from the shared
# nixos/configuration.nix.
{ config, lib, pkgs, inputs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      # Community hardware module for the Surface Go 1. Brings in the
      # linux-surface patched kernel, Kaby Lake CPU/GPU bits, ath10k WiFi
      # firmware override, SSD profile and Surface-specific power tuning.
      inputs.nixos-hardware.nixosModules.microsoft-surface-go
    ];

  # Pin the LTS variant of the linux-surface kernel.
  # Note: do NOT also set boot.kernelPackages here — the surface module
  # owns the kernel and the two would conflict.
  hardware.microsoft-surface.kernelVersion = "longterm";

  # IPU3 camera fixes layered on top of the linux-surface 6.19.8 kernel.
  # All three are needed together to actually get a working stream:
  #
  # 1. dw9719-add-i2c-device-id — re-adds the i2c_device_id table that
  #    upstream 6.19 dropped. On Surface, ipu_bridge instantiates the VCM
  #    as a plain I2C device with no ACPI/OF companion, so without this
  #    table the driver never binds, the OV8865 sub-notifier never
  #    completes, and (because v4l2-async completes hierarchically) the
  #    whole CIO2 notifier stalls — libcamera sees zero cameras.
  #    Source: https://lore.kernel.org/all/20260326174909.2746696-1-sakari.ailus@linux.intel.com/
  #    Tracked: https://github.com/linux-surface/linux-surface/pull/2123
  #
  # 2 & 3. ov8865-program-mode-on-stream-start / ov8865-drop-pm-ref-on-stream-fail.
  #    Once enumeration works, streaming still stalls with "payload length
  #    is X, received Y" in dmesg and `cam` hangs. Root cause: ov8865 only
  #    writes its sensor registers in the runtime-PM resume handler, while
  #    ipu_bridge gives the VCM a DL_FLAG_PM_RUNTIME link to the sensor.
  #    WirePlumber (and any libcamera consumer) holding the VCM subdev open
  #    pins the sensor runtime-active, so set_fmt() changes never reach
  #    the hardware — the sensor keeps streaming the previously-programmed
  #    mode while CIO2 expects the newly negotiated one.
  #    Tracked: https://github.com/linux-surface/linux-surface/pull/2169
  boot.kernelPatches = [
    {
      name = "dw9719-add-i2c-device-id";
      patch = ./patches/dw9719-add-i2c-device-id.patch;
    }
    {
      name = "ov8865-program-mode-on-stream-start";
      patch = ./patches/ov8865-program-mode-on-stream-start.patch;
    }
    {
      name = "ov8865-drop-pm-ref-on-stream-fail";
      patch = ./patches/ov8865-drop-pm-ref-on-stream-fail.patch;
    }
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  # IPU3 camera pipeline + Surface Go sensors + INT3472 power controllers.
  # These all need to be available so that when `ipu3-cio2` re-binds (see the
  # ipu3-rebind service below) the i2c sensors and their power rails are
  # already up and the bridge can wire the media graph.
  boot.kernelModules = [
    "kvm-intel"
    "ipu3_cio2"                   # CSI-2 receiver
    "ipu3_imgu"                   # image processing unit
    "ipu_bridge"                  # sensor <-> CSI2 ACPI bridge
    "intel_skl_int3472_discrete"  # power control for OV5693/OV8865
    "intel_skl_int3472_tps68470"  # power control for OV7251 (IR)
    "ov5693"                      # front (color) sensor
    "ov8865"                      # rear  (color) sensor
    "ov7251"                      # IR sensor (Windows Hello)
  ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "mitigations=off"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aa974abe-e7e5-4823-8012-d41a7a2cc7a3";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3693-8B1E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/rafael/sd" = {
    device = "/dev/disk/by-label/sd";
    fsType = "btrfs";
    options = [
      "x-systemd.automount"
      "noauto"
      "nofail"
      "x-systemd.idle-timeout=60"
      "x-systemd.device-timeout=5s"
      "x-systemd.mount-timeout=5s"
      "compress=zstd"
      "noatime"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /home/rafael/sd 0755 rafael users -"
  ];

  systemd.services.sd-storage-permissions = {
    description = "Ensure Rafael owns the SD card mount root";
    wantedBy = [ "home-rafael-sd.mount" ];
    after = [ "home-rafael-sd.mount" ];
    bindsTo = [ "home-rafael-sd.mount" ];
    serviceConfig.Type = "oneshot";
    script = ''
      chown rafael:users /home/rafael/sd
    '';
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5e97a962-a45b-43ac-b3a8-16da7888aa65"; }
    ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
  };

  # Kill the biggest memory hog before the whole tablet freezes when ART, a
  # browser and Synology Drive fight over 8 GB of RAM. Threshold 3% mirrors the
  # thinkpad-e14 config.
  services.earlyoom = {
    enable = true;
    freeMemThreshold = 3;
  };

  # Prefer keeping working sets in RAM; zram already provides cheap compressed
  # swap so cold pages still have somewhere to go without hitting the disk.
  boot.kernel.sysctl."vm.swappiness" = 10;

  fileSystems."/rafael_mounts" = {
    device = "//192.168.0.104/hdd";
    fsType = "cifs";
    options = let
      # Avoid blocking boot/switch/manual mount when the SMB server is unreachable.
      # requires/after network-online: an automount trigger that lands while the
      # network is restarting (typically mid nixos-rebuild switch) queues behind
      # the network coming back instead of failing with "Network is unreachable"
      # — which would mark the whole switch (and the daily nixos-upgrade) as
      # failed. _netdev alone only orders after network.target.
      mount_opts = "noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,x-systemd.requires=network-online.target,x-systemd.after=network-online.target";

    in ["${mount_opts},credentials=/home/rafael/.smb-secrets,uid=rafael,gid=100,_netdev" "cache=loose" "vers=3" "soft" "echo_interval=15" "fsc" "actimeo=30" ];
  };

  # Back the `fsc` mount option on /rafael_mounts with a real FS-Cache backend.
  # Without cachefilesd running, `fsc` on the CIFS mount is inert — ART re-reads
  # every thumbnail byte over SMB on each browse. With it enabled, RAW headers
  # and thumbnail data are cached on the local SSD (default: /var/cache/fscache)
  # and the file browser becomes near-instant on repeat visits.
  services.cachefilesd = {
    enable = true;
    extraConfig = ''
      brun 10%
      bcull 7%
      bstop 3%
      frun 10%
      fcull 7%
      fstop 3%
    '';
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Intel microcode is enabled by the kaby-lake submodule pulled in via
  # nixos-hardware/microsoft/surface/surface-go.

  networking.hostName = "bbtablet";

  # Locale / keymap (Danish) - host-specific
  i18n.defaultLocale = "en_DK.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };
  console.keyMap = "dk-latin1";
  services.xserver.xkb = {
    layout = "dk";
    variant = "";
  };

  # Desktop environment: GNOME + GDM
  services.xserver.enable = true;
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;

  programs.firefox.enable = true;

  # libcamera is required for the Surface Go's Intel IPU3 cameras (front + rear).
  # They do not present as standard UVC V4L2 devices, so raw v4l2 tools won't see
  # them — only libcamera (and apps/PipeWire that use it) can drive the pipeline.
  # WirePlumber's default `main` profile already loads `monitor.libcamera`
  # (hardware.video-capture), so installing libcamera here is enough for
  # PipeWire/WirePlumber to expose the cameras to portal-aware apps.
  environment.systemPackages = with pkgs; [
    libcamera
  ];

  # Surface Go IPU3 camera workaround.
  #
  # `ipu3-cio2` (the PCI CSI-2 receiver driver) probes very early in boot —
  # before the I2C sensor drivers (ov5693/ov8865/ov7251) and the INT3472
  # power controllers have attached. So when `ipu_bridge` runs at cio2 probe
  # time it has no sensors to link, and the resulting media graph has the
  # sensors and the four `ipu3-csi2` SINK pads sitting unconnected
  # (0 links). libcamera's IPU3 pipeline handler then enumerates zero
  # cameras even though `dmesg` says "Connected 3 cameras".
  #
  # Rebinding `ipu3-cio2` after userspace is up forces the bridge to re-run
  # with the sensors and INT3472 already probed, which actually creates the
  # fwnode links and makes the cameras visible to libcamera/PipeWire.
  systemd.services.ipu3-rebind = {
    description = "Rebind ipu3-cio2 so the IPU3 bridge picks up the sensors";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-modules-load.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      set -eu
      drv=/sys/bus/pci/drivers/ipu3-cio2
      # CIO2 (CSI-2 host controller) lives at 00:14.3 on Surface Go.
      # The IMGU (8086:1919) at 00:05.0 is a separate device handled by ipu3-imgu.
      dev=0000:00:14.3
      # Give the i2c sensor drivers and INT3472 a moment to settle.
      sleep 3
      if [ -e "$drv/$dev" ]; then
        echo "$dev" > "$drv/unbind"
        sleep 1
      fi
      echo "$dev" > "$drv/bind"
    '';
  };

  # --- Surface Go specific tuning ---

  # Touchscreen + pen via the Intel Precise Touch & Stylus daemon.
  services.iptsd.enable = true;

  # Auto-rotation: GNOME has to be nudged into claiming the accelerometer.
  #
  # The sensor stack itself is healthy. ISH enumerates, hid-sensor-hub binds,
  # and iio-sensor-proxy exports accel_3d correctly -- claiming it by hand with
  # monitor-sensor returns an orientation immediately. The fault is on mutter's
  # side: it does not reliably claim the accelerometer from
  # net.hadess.SensorProxy, neither after a fresh boot nor after a resume. With
  # no client holding a claim the proxy stops computing orientation,
  # AccelerometerOrientation reads "undefined", and the screen never rotates.
  #
  # Resume makes this constant on a Surface Go, because folding the Type Cover
  # back into tablet position registers as a lid close and suspends the machine.
  # HandleLidSwitch is deliberately left at its "suspend" default -- closing the
  # cover *should* suspend -- so rotation dies at exactly the moment you switch
  # into the mode that needs it.
  #
  # Restarting the proxy makes its D-Bus name drop and reappear, which is what
  # makes mutter claim the sensor. Verified by hand: `systemctl restart
  # iio-sensor-proxy` on a dead session brings rotation straight back.
  #
  # The restart must happen *after* mutter is running, or there is nobody to
  # react to the name returning. graphical.target is reached when GDM starts,
  # well before login, so wait for gnome-shell itself rather than the target.
  systemd.services.iio-sensor-proxy-reclaim = {
    description = "Restart iio-sensor-proxy so GNOME claims the accelerometer";
    wantedBy = [
      "graphical.target"
      "suspend.target"
      "hibernate.target"
      "hybrid-sleep.target"
      "suspend-then-hibernate.target"
    ];
    # Being ordered After a sleep target means this runs on the way back *up*,
    # once the machine has actually resumed -- not on the way down.
    after = [
      "graphical.target"
      "suspend.target"
      "hibernate.target"
      "hybrid-sleep.target"
      "suspend-then-hibernate.target"
    ];
    path = [ pkgs.procps ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -eu
      # On resume gnome-shell is already up and this returns on the first pass.
      # At boot it covers however long the user spends at the GDM prompt, then
      # gives up after ~2min so the unit does not linger on a headless boot.
      for _ in $(seq 1 60); do
        if pgrep -f gnome-shell > /dev/null 2>&1; then
          # Let mutter finish its own sensor setup before yanking the name.
          sleep 3
          # try-restart: do nothing if the proxy is not running, rather than
          # starting a service that was deliberately stopped.
          systemctl try-restart iio-sensor-proxy.service
          exit 0
        fi
        sleep 2
      done
    '';
  };

  # Bluetooth (Marvell module on Surface Go).
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;

  # Surface Go is fanless; thermald keeps it under throttle thresholds
  # without clamping frequency too aggressively.
  services.thermald.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Backlight + power keys (programs.light was removed from nixpkgs).
  hardware.acpilight.enable = true;
  services.acpid.enable = true;

  # Touch ergonomics for GNOME on Wayland.
  services.libinput = {
    enable = true;
    touchpad.naturalScrolling = true;
  };

  # Intel Kaby Lake GPU acceleration (VA-API video decode).
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      libva-vdpau-driver
      libvdpau-va-gl
    ];
  };

  # Pull in non-redistributable firmware as well (covers IPU3 cameras).
  hardware.enableAllFirmware = true;

  services.syncthing = {
    user = "rafael";
    group = "users";
    dataDir = "/home/rafael";
    enable = true;
  };

  # ssh_config is read by every user including root (the nix-daemon's UID).
  # Point at /etc/nix/nixbuild_ed25519 rather than /home/rafael/.ssh/id_ed25519
  # so the daemon isn't reaching into a per-user home dir; the file needs to be
  # provisioned once out-of-band (see the assertion + activation script below).
  # `User rafael` matters here: nix-daemon builds get the user from the
  # `ssh-ng://rafael@...` URI baked into /etc/nix/machines, but manual
  # invocations like `nix store info --store ssh-ng://eu.nixbuild.net` have
  # no user in the URI and would otherwise default to `root`, failing with
  # `root@eu.nixbuild.net: Permission denied (publickey)`. Setting it here
  # covers both call sites. (nixbuild.net ignores the username and identifies
  # clients purely by SSH key.)
#   programs.ssh.extraConfig = ''
#   Host eu.nixbuild.net
#   User rafael
#   PubkeyAcceptedKeyTypes ssh-ed25519
#   ServerAliveInterval 60
#   IdentityFile /etc/nix/nixbuild_ed25519
# '';

  # programs.ssh.knownHosts = {
  #   nixbuild = {
  #     hostNames = [ "eu.nixbuild.net" ];
  #     publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPIQCZc54poJ8vqawd8TraNryQeJnvH1eLpIDgbiqymM";
  #   };
  # };

  # nix = {
  #   distributedBuilds = true;
  #   # Have nixbuild.net's builders fetch from public substituters directly
  #   # instead of streaming closures back through this tablet's uplink.
  #   extraOptions = ''
  #     builders-use-substitutes = true
  #   '';
  #   buildMachines = [
  #     { hostName = "eu.nixbuild.net";
  #       # nixbuild.net identifies clients by SSH key, not username; any user
  #       # name works. Pinning it here avoids the daemon falling back to `root`
  #       # (which would then look for /root/.ssh/config, not /etc/ssh/ssh_config
  #       # in some code paths).
  #       sshUser = "rafael";
  #       sshKey = "/etc/nix/nixbuild_ed25519";
  #       # ssh-ng is required for nixbuild.net's remote-store protocol; the plain
  #       # `ssh` protocol works too but ssh-ng streams derivations more
  #       # efficiently and is what nixbuild's docs recommend.
  #       protocol = "ssh-ng";
  #       system = "x86_64-linux";
  #       maxJobs = 100;
  #       supportedFeatures = [ "benchmark" "big-parallel" "kvm" ];
  #     }
  #   ];
  # };

  # Fail the rebuild early with a clear message if the key isn't in place, so
  # we don't ship a config where every build silently falls back to local.
  # The source is ~/.ssh/my-nixbuild-key, NOT id_ed25519 — the latter is a
  # personal key that isn't registered on nixbuild.net.
  # First-time setup on this host:
  #     sudo install -m 0600 -o root -g root \
  #       /home/rafael/.ssh/my-nixbuild-key /etc/nix/nixbuild_ed25519
  system.activationScripts.checkNixbuildKey.text = ''
    if [ ! -r /etc/nix/nixbuild_ed25519 ]; then
      echo "WARN: /etc/nix/nixbuild_ed25519 missing — remote builds to eu.nixbuild.net will fail." >&2
      echo "      Install with: sudo install -m 0600 -o root -g root /home/rafael/.ssh/my-nixbuild-key /etc/nix/nixbuild_ed25519" >&2
    fi
  '';
}
