;; (package! isar-mode)
;; (package! isar-goal-mode)
;; (package! lsp-isar)
;; (package! lsp-isar-parse-args)
(package! session-async)
(package! academic-phrases)
(package! flycheck-languagetool)
(package! cycle-themes)
(package! quail :disable t)
;; (package! company-posframe)
