# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "bfq" "v4l2loopback" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];

  boot.postBootCommands = ''
   echo mq-deadline > /sys/block/sda/queue/scheduler
   echo mq-deadline > /sys/block/sdb/queue/scheduler
   echo 1 > /sys/block/sda/queue/iosched/fifo_batch
   echo 1 > /sys/block/sdb/queue/iosched/fifo_batch
  '';

  boot.kernelPackages = pkgs.linuxPackages_zen;

 boot.kernel.sysctl = {
    "sched_latency_ns" = "1000000";
    "sched_min_granularity_ns" = "100000";
    "sched_migration_cost_ns"  = "7000000";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/96082114-504a-43e6-8a32-7c0b49097e8a";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/bighd" =
    { device = "/dev/disk/by-uuid/327c26b4-79a8-4243-9fd0-e75f5d82e892";
      fsType = "ext4";
    };

  fileSystems."/bighd2" =
    { device = "/dev/disk/by-label/bighd2";
      fsType = "ntfs";
    };

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "mode=1777" "lazytime" "nosuid" "nodev" ];
  };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/63d991d0-8b79-4821-9cc3-0d28993d4d7d"; }
  #   ];

  networking.hostName = "desktop";

  programs.steam.enable = true;

  # Xserver basic
  services.xserver = {
    layout = "us";
    xkbVariant = "intl";

    libinput = {
      enable = true;

      mouse = {
        disableWhileTyping = true;
        accelProfile = "adaptive";
        accelSpeed = "0.1";
        calibrationMatrix = ".5 0 0 0 .5 0 0 0 1";
      };
    };

    videoDrivers = [ "nvidia" ];

    serverLayoutSection = ''
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
  '';

    deviceSection = ''
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 6GB"
  '';

    monitorSection = ''
    VendorName     "Unknown"
    ModelName      "LG Electronics LG TV SSCR"
    HorizSync       30.0 - 135.0
    VertRefresh     24.0 - 120.0
    Option         "DPMS"
  '';

    screenSection = ''
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "DPI" "96 x 96"
    Option         "nvidiaXineramaInfoOrder" "DFP-2"
    Option         "metamodes" "HDMI-0: 4096x2160_60 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-0: 1920x1080_144 +4096+1080 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
  '';

  };

  virtualisation.virtualbox.host.enable = true;
  users.extraGroups.vboxusers.members = [ "user-with-access-to-virtualbox" ];

  # Docker config
  virtualisation.docker = {
    enable = true;
    enableOnBoot = false;
  };
  #To support circleci-cli
  systemd.enableUnifiedCgroupHierarchy = false;

  services.syncthing = {
    user = "rafael";
    group = "users";
    dataDir = "/home/rafael";
    enable = true;
    relay.enable = true;
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Enable cron service
  services.cron = {
    enable = true;
    systemCronJobs = [
      "*/1 0 * * *     rafael    cd /home/rafael/zsh_history; for c in zsh_history.sync-conflict-*; do git merge-file zsh_history empty.history $c;done; rm zsh_history.sync-conflict-*"
    ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
