# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "bfq" ];
  boot.extraModulePackages = [ ];

  boot.postBootCommands = ''
   echo bfq > /sys/block/sda/queue/scheduler
   echo bfq > /sys/block/sdb/queue/scheduler
  '';

  boot.kernelPackages = pkgs.linuxPackages_zen;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/96082114-504a-43e6-8a32-7c0b49097e8a";
      fsType = "ext4";
    };

  fileSystems."/bighd" =
    { device = "/dev/disk/by-uuid/327c26b4-79a8-4243-9fd0-e75f5d82e892";
      fsType = "ext4";
    };

  fileSystems."/bighd2" =
    { device = "/dev/disk/by-label/bighd2";
      fsType = "ntfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/63d991d0-8b79-4821-9cc3-0d28993d4d7d"; }
    ];

  programs.steam.enable = true;

  # Xserver basic
  services.xserver = {
    exportConfiguration = true;

    libinput = {
      enable = true;

      mouse = {
        disableWhileTyping = true;
        accelProfile = "adaptive";
        accelSpeed = "0.1";
        calibrationMatrix = ".5 0 0 0 .5 0 0 0 1";
      };
    };

    videoDrivers = [ "nvidia" ];

    serverLayoutSection = ''
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
  '';

    deviceSection = ''
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1060 6GB"
  '';

    monitorSection = ''
    VendorName     "Unknown"
    ModelName      "LG Electronics LG TV SSCR"
    HorizSync       30.0 - 135.0
    VertRefresh     24.0 - 120.0
    Option         "DPMS"
  '';

    screenSection = ''
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "DPI" "96 x 96"
    Option         "nvidiaXineramaInfoOrder" "DFP-2"
    Option         "metamodes" "HDMI-0: 4096x2160_60 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-0: 1920x1080_144 +4096+1080 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
        Depth       24
    EndSubSection
  '';

  };

  virtualisation.virtualbox.host.enable = true;
  users.extraGroups.vboxusers.members = [ "user-with-access-to-virtualbox" ];

  # Docker config
  virtualisation.docker = {
    enable = true;
    enableOnBoot = false;
  };
  #To support circleci-cli
  systemd.enableUnifiedCgroupHierarchy = false;

  services.syncthing = {
    user = "rafael";
    group = "users";
    dataDir = "/home/rafael";
    enable = true;
    relay.enable = true;
  };


  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
