{ pkgs, pkgsUnstable, ...}:

{
  home.packages = [
    pkgs.vlc
    pkgs.loupe
    pkgs.onlyoffice-desktopeditors
    pkgs.dialect
    pkgs.remmina
    pkgs.ffmpegthumbnailer
    pkgs.libappindicator
    pkgs.gdk-pixbuf
    pkgs.file-roller
    pkgs.gparted
    pkgs.lshw-gui
    pkgs.seahorse
    pkgs.freerdp
    pkgs.xdotool
    pkgs.lxrandr
    pkgs.srandrd
    pkgs.zoom-us              # picks up libpw-v4l2 via global LD_PRELOAD in home.nix
    pkgsUnstable.signal-desktop
    pkgs.element-desktop
    pkgs.drawio
    pkgs.qalculate-qt
    pkgs.chromium
    pkgs.koreader
    pkgs.zotero
    pkgs.simple-scan
    pkgs.snapshot
    pkgs.thunderbird
    pkgs.kdePackages.kalk
    pkgs.xpra
    pkgs.proton-vpn
    pkgs.papers
    pkgs.mission-center
    pkgs.baobab
    pkgs.wl-clipboard
    pkgs.satty
    pkgs.pdfarranger
  ];

  # Chromium command-line flags. Chromium reads ~/.config/chromium-flags.conf
  # on startup and appends each line as an extra argv. Keep Chromium native on
  # Wayland at fractional scale and enable the WebRTC PipeWire camera backend.
  home.file.".config/chromium-flags.conf".text = ''
    --ozone-platform-hint=auto
    --enable-features=WaylandWindowDecorations,WebRtcPipeWireCamera
  '';

  # LibreWolf: force the WebRTC PipeWire camera backend on. The same pref
  # set via programs.librewolf.settings goes into librewolf.overrides.cfg as
  # `defaultPref`, which is read too late for the `_AtStartup` static-pref
  # mirror - LibreWolf still picks the V4L2 path and enumerates zero cameras
  # on IPU3 hardware (Surface Go). Writing it as `user_pref` in the profile's
  # user.js is read early enough and actually flips the backend selection.
  #
  # NOTE: the profile dir name is the one auto-generated by LibreWolf on first
  # run. If the profile is ever deleted/recreated, update this path to match
  # the new random prefix (see ~/.librewolf/profiles.ini).
  home.file.".librewolf/zeku5s1n.default/user.js".text = ''
    // Managed by home-manager. See graphical-apps/everyday.nix.
    user_pref("media.webrtc.camera.allow-pipewire", true);
  '';

  programs.brave = {
    enable = true;
    # Keep Brave native on Wayland at fractional scale and enable the WebRTC
    # PipeWire camera backend for portal/libcamera cameras.
    commandLineArgs = [
      "--ozone-platform-hint=auto"
      "--enable-features=WaylandWindowDecorations,WebRtcPipeWireCamera"
    ];
    extensions = [
      {id = "nngceckbapebfimnlniiiahkandclblb";} # Bitwarden
      {id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";} # uBlock Origin
      {id = "dbepggeogbaibhgnhhndojpepiihcmeb";} # Vimium
      {id = "ekhagklcjbdpajgpjgmbionohlpdbjgc";} # Zotero
      {id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";} # Dark reader
      {id = "dphilobhebphkdjbpfohgikllaljmgbn";} # Simple login
      {id = "oldceeleldhonbafppcapldpdifcinji";} # LanguageTool
      {id = "mdjildafknihdffpkfmmpnpoiajfjnjd";} # Consent-O-Matic
    ];
  };

  programs.librewolf = {
    enable = true;
    settings = {
      "webgl.disabled" = false;
      "privacy.resistFingerprinting" = false;
      "privacy.clearOnShutdown.history" = false;
      "privacy.clearOnShutdown.cookies" = false;
      "network.cookie.lifetimePolicy" = 0;
    };
  };
}
