{ pkgs, pkgsUnstable, lib, ...}:

{
  home.packages = [
    pkgs.vlc
    pkgs.loupe
    pkgs.onlyoffice-desktopeditors
    pkgs.dialect
    pkgs.remmina
    pkgs.ffmpegthumbnailer
    pkgs.libappindicator
    pkgs.gdk-pixbuf
    pkgs.file-roller
    pkgs.gparted
    pkgs.lshw-gui
    pkgs.seahorse
    pkgs.freerdp
    pkgs.xdotool
    pkgs.lxrandr
    pkgs.srandrd
    pkgs.zoom-us              # picks up libpw-v4l2 via global LD_PRELOAD in home.nix
    pkgsUnstable.signal-desktop
    pkgs.element-desktop
    pkgs.drawio
    pkgs.qalculate-qt
    pkgs.chromium
    pkgs.koreader
    pkgs.zotero
    pkgs.simple-scan
    pkgs.snapshot
    pkgs.thunderbird
    pkgs.kdePackages.kalk
    pkgs.xpra
    pkgs.proton-vpn
    pkgs.papers
    pkgs.mission-center
    pkgs.baobab
    pkgs.wl-clipboard
    pkgs.satty
    pkgs.pdfarranger
  ];

  # Chromium command-line flags. Chromium reads ~/.config/chromium-flags.conf
  # on startup and appends each line as an extra argv. Keep Chromium native on
  # Wayland at fractional scale and enable the WebRTC PipeWire camera backend.
  home.file.".config/chromium-flags.conf".text = ''
    --ozone-platform-hint=auto
    --enable-features=WaylandWindowDecorations,WebRtcPipeWireCamera
  '';

  # LibreWolf: force the WebRTC PipeWire camera backend on. The same pref
  # set via programs.librewolf.settings goes into librewolf.overrides.cfg as
  # `defaultPref`, which is read too late for the `_AtStartup` static-pref
  # mirror - LibreWolf still picks the V4L2 path and enumerates zero cameras
  # on IPU3 hardware (Surface Go). Writing it as `user_pref` in the profile's
  # user.js is read early enough and actually flips the backend selection.
  #
  # NOTE: the profile dir name is the one auto-generated by LibreWolf on first
  # run. If the profile is ever deleted/recreated, update this path to match
  # the new random prefix (see ~/.librewolf/profiles.ini).
  home.file.".librewolf/zeku5s1n.default/user.js".text = ''
    // Managed by home-manager. See graphical-apps/everyday.nix.
    user_pref("media.webrtc.camera.allow-pipewire", true);
  '';

  programs.brave = {
    enable = true;
    # Keep Brave native on Wayland at fractional scale and enable the WebRTC
    # PipeWire camera backend for portal/libcamera cameras.
    commandLineArgs = [
      "--ozone-platform-hint=auto"
      "--enable-features=WaylandWindowDecorations,WebRtcPipeWireCamera"
    ];
    extensions = [
      {id = "nngceckbapebfimnlniiiahkandclblb";} # Bitwarden
      {id = "cjpalhdlnbpafiamejdnhcphjbkeiagm";} # uBlock Origin
      {id = "dbepggeogbaibhgnhhndojpepiihcmeb";} # Vimium
      {id = "ekhagklcjbdpajgpjgmbionohlpdbjgc";} # Zotero
      {id = "eimadpbcbfnmbkopoojfekhnkhdbieeh";} # Dark reader
      {id = "dphilobhebphkdjbpfohgikllaljmgbn";} # Simple login
      {id = "oldceeleldhonbafppcapldpdifcinji";} # LanguageTool
      {id = "mdjildafknihdffpkfmmpnpoiajfjnjd";} # Consent-O-Matic
    ];
  };

  programs.librewolf = {
    enable = true;
    settings = {
      "webgl.disabled" = false;
      # "Fix major site issues (recommended)": disable ResistFingerprinting
      # (the aggressive protection that breaks many sites).
      "privacy.resistFingerprinting" = false;
      # "Fix minor site issues": disable the lighter FingerprintingProtection.
      "privacy.fingerprintingProtection" = false;
      "privacy.clearOnShutdown.history" = false;
      "privacy.clearOnShutdown.cookies" = false;
      "network.cookie.lifetimePolicy" = 0;
      # DRM playback (Widevine) always on. LibreWolf disables it by default and
      # locks the UI toggle, so it has to be set here.
      "media.eme.enabled" = true;
      "media.gmp-widevinecdm.enabled" = true;
      # Spell-check dictionaries: English (US) + Brazilian Portuguese. Firefox
      # scans this directory for hunspell .dic/.aff files.
      "spellchecker.dictionary_path" = "${pkgs.symlinkJoin {
        name = "librewolf-hunspell-dicts";
        paths = [ pkgs.hunspellDicts.en_US pkgs.hunspellDicts.pt_BR ];
      }}/share/hunspell";
    };
    # A home-manager-managed profile is required for catppuccin/nix to install
    # the Catppuccin browser theme (it hooks into a named profile). NOTE: this
    # becomes the default profile; the previously auto-generated profile still
    # exists but is no longer default (switch back via about:profiles if needed).
    profiles.default = {
      id = 0;
      isDefault = true;
      extensions = {
        # Acknowledge, once and for all, that this profile's extension policy is
        # managed declaratively (Catppuccin theme + the extensions below).
        # mkForce so it wins over whatever catppuccin.librewolf sets - this flag
        # is what the "override all previous extensions" assertion wants, and
        # setting it here means changing extensions never re-triggers it.
        force = lib.mkForce true;
        # Force-install extensions from AMO via the ExtensionSettings policy
        # (auto-updating; no extra flake input needed).
        settings = {
          # Bitwarden password manager
          "{446900e4-71c2-419f-a6a7-df9c091e268b}".settings = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi";
            installation_mode = "force_installed";
          };
          # Dark Reader
          "addon@darkreader.org".settings = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi";
            installation_mode = "force_installed";
          };
        };
      };
    };
  };

  # Catppuccin Mocha (mauve) theme for the profile. The extension-override
  # acknowledgement is handled by extensions.force above.
  catppuccin.librewolf.profiles.default.enable = true;
}
