# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config,
  lib,
  pkgs,
  inputs,
  system ? pkgs.system,
  modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.kernelPackages = pkgs.linuxPackages;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.supportedFilesystems = [ "nfs" ];

  # boot.blacklistedKernelModules = [ "rtl8821cu" "rtw88_8821cu" ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [ rtl88xxau-aircrack ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8821au ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8821cu ];
  hardware.wirelessRegulatoryDatabase = true;

  hardware.enableRedistributableFirmware = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    input = {
      General = {
        UserspaceHID = true;
      };
    };
    settings = {
      General = {
        Experimental = true;
        # ControllerMode = "bredr";
      };
    };
  };

  boot.kernelParams = [
    "mitigations=off"
    "kvm.enable_virt_at_load=0"
    "btusb.enable_autosuspend=n"
    "nvidia-drm.modeset=1"
    "nvidia-drm.fbdev=1"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2409ac65-2c0c-4321-bc6a-777e2097f025";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/1A36-4B87";
      fsType = "vfat";
    };


  fileSystems."/hdd" =
    { device = "/dev/disk/by-label/hdd";
      fsType = "btrfs";
      options = [ "discard=async" "compress=zstd" "noatime" "datacow" ];
    };

  fileSystems."/rafael_mounts" = {
    device = "//192.168.0.104/hdd";
    fsType = "cifs";
    options = let
      # Avoid blocking boot/switch/manual mount when the SMB server is unreachable.
      # requires/after network-online: an automount trigger that lands while the
      # network is restarting (typically mid nixos-rebuild switch) queues behind
      # NetworkManager-wait-online instead of failing with "Network is
      # unreachable" — which would mark the whole switch (and the daily
      # nixos-upgrade) as failed. _netdev alone only orders after network.target.
      # No idle-timeout: cosmic-files stats every mount point on launch, so an
      # expired automount made opening it block on a fresh SMB mount (5s+ when
      # the server is slow to answer). Mounting once and staying mounted is
      # safe here — `soft` turns a dead server into EIO instead of a hang.
      mount_opts = "noauto,nofail,x-systemd.automount,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,x-systemd.requires=network-online.target,x-systemd.after=network-online.target";

    in ["${mount_opts},credentials=/home/rafael/.smb-secrets,uid=1000,gid=100,_netdev" "cache=loose" "vers=3" "soft" "echo_interval=15" "fsc" "actimeo=30" ];
  };

  # Back the `fsc` mount option on /rafael_mounts with a real FS-Cache backend.
  # Without cachefilesd the `fsc` above is inert: the cachefiles module is never
  # loaded and /var/cache/fscache never exists, so every browse re-reads the
  # same bytes over the network. Same block as bbtablet and thinkpad-e14.
  services.cachefilesd = {
    enable = true;
    extraConfig = ''
      brun 10%
      bcull 7%
      bstop 3%
      frun 10%
      fcull 7%
      fstop 3%
    '';
  };

  # systemd = {
  #   extraConfig = "DefaultTimeoutStopSec=10s";
  # };

  services.earlyoom = {
    enable = true;
    freeMemThreshold = 1;
  };
  # earlyoom is the single OOM killer; don't run systemd-oomd alongside it.
  systemd.oomd.enable = false;

  swapDevices = [ ];
  zramSwap.enable = true;
  zramSwap.algorithm = "zstd";
  zramSwap.priority = 10;

  programs.xwayland.enable = true;
  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"];

  # NVIDIA + Wayland environment variables
  environment.sessionVariables = {
    # Required for Wayland compositors with NVIDIA
    GBM_BACKEND = "nvidia-drm";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    # Electron / Chromium apps: use Wayland natively instead of XWayland
    NIXOS_OZONE_WL = "1";
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    COSMIC_DATA_CONTROL_ENABLED = "1";
    # Cursor rendering fix for NVIDIA on Wayland
    WLR_NO_HARDWARE_CURSORS = "1";
  };
  programs.steam.enable = true;

  hardware.nvidia = {

    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead 
    # of just the bare essentials.
    powerManagement.enable = false;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of 
    # supported GPUs is at: 
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus 
    # Only available from driver 515.43.04+
    # Recommended module for Turing+ on modern drivers. On this host it improved
    # reclocking responsiveness under Wayland/COSMIC at 4K.
    open = true;

    # Keep the GPU initialized so the clock locks below persist before login.
    nvidiaPersistenced = true;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;
    forceFullCompositionPipeline = false;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = pkgs.linuxPackages.nvidiaPackages.stable;
  };

  systemd.services.nvidia-desktop-clocks = {
    description = "Lock NVIDIA clocks for 4K desktop responsiveness";
    wantedBy = [ "multi-user.target" ];
    after = [ "nvidia-persistenced.service" "systemd-udev-settle.service" ];
    wants = [ "nvidia-persistenced.service" "systemd-udev-settle.service" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = [
        "${config.hardware.nvidia.package.bin}/bin/nvidia-smi --lock-memory-clocks=7001,7001"
        "${config.hardware.nvidia.package.bin}/bin/nvidia-smi --lock-gpu-clocks=1500,2100"
      ];
      ExecStop = [
        "-${config.hardware.nvidia.package.bin}/bin/nvidia-smi --reset-gpu-clocks"
        "-${config.hardware.nvidia.package.bin}/bin/nvidia-smi --reset-memory-clocks"
      ];
    };
  };

  powerManagement = {
    cpuFreqGovernor = "performance";
  };
  # Printer and scanner stuff
  services.printing = {
    listenAddresses = [ "*:631" ];
    allowFrom = [ "all" ];
    browsing = true;
    defaultShared = true;
    openFirewall = true;
  };
  services.printing.drivers = [ pkgs.carps-cups pkgs.gutenprint pkgs.gutenprintBin pkgs.hplip pkgs.cnijfilter2 ];


  services.syncthing = {
    user = "rafael";
    group = "users";
    dataDir = "/home/rafael";
    enable = true;
  };

  # Docker config
  virtualisation.docker = {
    enable = true;
    enableOnBoot = false;
  };
  systemd.services.docker.serviceConfig.KillMode = "mixed";

  nix.settings = {
    substituters = [ "https://winapps.cachix.org/" ];
    trusted-public-keys = [ "winapps.cachix.org-1:HI82jWrXZsQRar/PChgIx1unmuEsiQMQq+zt05CD36g=" ];
    trusted-users = [ "rafael" ]; # replace with your username
  };

  environment.systemPackages =
    let
      winappsPackages = inputs.winapps.packages.${pkgs.stdenv.hostPlatform.system};
      winapps = winappsPackages.winapps.overrideAttrs (oldAttrs: {
        # The Docker backend connects to a local Windows VM on 127.0.0.1.
        # Its self-signed RDP certificate changes when the VM is recreated,
        # and upstream setup uses non-interactive /cert:tofu checks.
        postPatch = (oldAttrs.postPatch or "") + ''
          substituteInPlace setup.sh \
            --replace-fail /cert:tofu /cert:ignore
        '';
      });
    in
    [
      winapps
      winappsPackages.winapps-launcher # optional
      pkgs.cifs-utils
    ];

  # virtualisation.virtualbox.host.enable = true;
  # virtualisation.virtualbox.host.enableExtensionPack = true;
  # virtualisation.virtualbox.guest.dragAndDrop = true;
  # nixpkgs.config.virtualbox.host.enableExtensionPack = true;

  services.cloudflared = {
    enable = true;
    tunnels = {
      "d25ffd7d-c129-4ad6-9053-bed47e3f4543" = {
        credentialsFile = "/home/rafael/.cloudflared/d25ffd7d-c129-4ad6-9053-bed47e3f4543.json";
        default = "http_status:404";
      };
    };
  };


  users.extraGroups.vboxusers.members = [ "rafael" "kv" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0u7.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  networking.hostName = "bbstation";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Desktop environment: KDE Plasma 6 + COSMIC greeter
  services.xserver.enable = true;
  services.displayManager = {
    defaultSession = "cosmic";
    cosmic-greeter.enable = true;
  };
  services.desktopManager.cosmic.enable = true;
  services.system76-scheduler.enable = true;


}
